// Auto-generated by scripts/generate-catalog.mjs — do not edit by hand.
// Source: E:\allinone - Copy (2)\src\AllInOne\app_catalog.json

export type CatalogApp = {
  name: string;
  wingetId: string;
  category: string;
};

export type Profile = {
  name: string;
  description: string;
  appCount: number;
  builtin: boolean;
  apps: string[];
};

export const catalogVersion = "2.5.0";

export const categories = [
  "Browsers",
  "Communication",
  "Media Players",
  "Content Creation",
  "Development",
  "Compression",
  "Utilities",
  "System Monitoring",
  "Security",
  "Networking & VPN",
  "Remote Desktop",
  "Virtualization",
  "Gaming",
  "Office & Productivity",
  "System Cleanup",
  "AI Tools",
  "Database",
  "Cloud Storage",
  "Education",
  "System Tools",
  "Graphics & Design",
  "Direct Downloads",
  "SDKs & Runtimes",
] as const;

export const catalogStats = {
  totalApps: 336,
  totalCategories: 23,
} as const;

export const catalogApps: CatalogApp[] = [
  {
    name: "1Password",
    wingetId: "AgileBits.1Password",
    category: "Security",
  },
  {
    name: "7-Zip",
    wingetId: "7zip.7zip",
    category: "Compression",
  },
  {
    name: "7-Zip ZStandard",
    wingetId: "mcmilk.7zip-zstd",
    category: "Compression",
  },
  {
    name: "Adobe Acrobat Pro",
    wingetId: "Adobe.Acrobat.Pro.64-bit",
    category: "Office & Productivity",
  },
  {
    name: "Adobe Acrobat Reader",
    wingetId: "Adobe.Acrobat.Reader.64-bit",
    category: "Office & Productivity",
  },
  {
    name: "Adobe Illustrator",
    wingetId: "Adobe.Illustrator",
    category: "Graphics & Design",
  },
  {
    name: "Adobe Photoshop",
    wingetId: "Adobe.Photoshop",
    category: "Graphics & Design",
  },
  {
    name: "Adoptium Temurin 17",
    wingetId: "EclipseAdoptium.Temurin.17.JDK",
    category: "Development",
  },
  {
    name: "Affinity Designer 2",
    wingetId: "Serif.AffinityDesigner2",
    category: "Content Creation",
  },
  {
    name: "Affinity Photo 2",
    wingetId: "Serif.AffinityPhoto2",
    category: "Content Creation",
  },
  {
    name: "Affinity Photo duplicate",
    wingetId: "Serif.AffinityPhoto",
    category: "Graphics & Design",
  },
  {
    name: "Agent Ransack",
    wingetId: "Mythicsoft.AgentRansack",
    category: "Utilities",
  },
  {
    name: "AIDA64 Extreme",
    wingetId: "FinalWire.AIDA64.Extreme",
    category: "System Monitoring",
  },
  {
    name: "AIMP",
    wingetId: "AIMP.AIMP",
    category: "Media Players",
  },
  {
    name: "Amazon Corretto JDK 17",
    wingetId: "Amazon.Corretto.17.JDK",
    category: "SDKs & Runtimes",
  },
  {
    name: "Amazon Corretto JDK 21",
    wingetId: "Amazon.Corretto.21.JDK",
    category: "SDKs & Runtimes",
  },
  {
    name: "Android NDK",
    wingetId: "Google.AndroidNDK",
    category: "SDKs & Runtimes",
  },
  {
    name: "Android SDK Platform Tools",
    wingetId: "Google.PlatformTools",
    category: "SDKs & Runtimes",
  },
  {
    name: "Android Studio",
    wingetId: "Google.AndroidStudio",
    category: "Development",
  },
  {
    name: "Anki",
    wingetId: "Ankitects.Anki",
    category: "Education",
  },
  {
    name: "Ant",
    wingetId: "Apache.Ant",
    category: "SDKs & Runtimes",
  },
  {
    name: "AnyDesk",
    wingetId: "AnyDesk.AnyDesk",
    category: "Remote Desktop",
  },
  {
    name: "Arc Browser",
    wingetId: "TheBrowserCompany.Arc",
    category: "Browsers",
  },
  {
    name: "Arduino IDE 2",
    wingetId: "ArduinoSA.IDE.stable",
    category: "SDKs & Runtimes",
  },
  {
    name: "Audacity",
    wingetId: "Audacity.Audacity",
    category: "Content Creation",
  },
  {
    name: "Auslogics Disk Defrag",
    wingetId: "Auslogics.DiskDefrag",
    category: "System Cleanup",
  },
  {
    name: "AutoHotkey",
    wingetId: "AutoHotkey.AutoHotkey",
    category: "Utilities",
  },
  {
    name: "Avast Free Antivirus",
    wingetId: "Avast.AvastFreeAntivirus",
    category: "Security",
  },
  {
    name: "Avast Secure Browser",
    wingetId: "Avast.SecureBrowser",
    category: "Browsers",
  },
  {
    name: "AVG Antivirus",
    wingetId: "AVG.AVGAntivirusFree",
    category: "Security",
  },
  {
    name: "Avira Free",
    wingetId: "Avira.Antivirus",
    category: "Security",
  },
  {
    name: "AWS CLI",
    wingetId: "Amazon.AWSCLI",
    category: "Development",
  },
  {
    name: "Azure CLI",
    wingetId: "Microsoft.AzureCLI",
    category: "Development",
  },
  {
    name: "Azure Data Studio",
    wingetId: "Microsoft.AzureDataStudio",
    category: "Database",
  },
  {
    name: "Bandizip",
    wingetId: "Bandisoft.Bandizip",
    category: "Compression",
  },
  {
    name: "Battle.net",
    wingetId: "Blizzard.BattleNet",
    category: "Gaming",
  },
  {
    name: "BellSoft Liberica JDK 17",
    wingetId: "BellSoft.LibericaJDK.17",
    category: "SDKs & Runtimes",
  },
  {
    name: "BellSoft Liberica JDK 21",
    wingetId: "BellSoft.LibericaJDK.21",
    category: "SDKs & Runtimes",
  },
  {
    name: "Bitwarden",
    wingetId: "Bitwarden.Bitwarden",
    category: "Security",
  },
  {
    name: "BleachBit",
    wingetId: "BleachBit.BleachBit",
    category: "System Cleanup",
  },
  {
    name: "Blender",
    wingetId: "BlenderFoundation.Blender",
    category: "Content Creation",
  },
  {
    name: "Box Drive",
    wingetId: "Box.BoxDrive",
    category: "Cloud Storage",
  },
  {
    name: "Brave Browser",
    wingetId: "Brave.Brave",
    category: "Browsers",
  },
  {
    name: "Bulk Rename Utility",
    wingetId: "TGRMNSoftware.BulkRenameUtility",
    category: "Utilities",
  },
  {
    name: "Bun Runtime",
    wingetId: "Oven-sh.Bun",
    category: "SDKs & Runtimes",
  },
  {
    name: "Calibre",
    wingetId: "calibre.calibre",
    category: "Office & Productivity",
  },
  {
    name: "Canva Desktop",
    wingetId: "Canva.CanvaDesktop",
    category: "Content Creation",
  },
  {
    name: "CCleaner",
    wingetId: "Piriform.CCleaner",
    category: "System Cleanup",
  },
  {
    name: "Chocolatey GUI",
    wingetId: "Chocolatey.ChocolateyGUI",
    category: "System Tools",
  },
  {
    name: "Chrome Remote Desktop",
    wingetId: "Google.ChromeRemoteDesktop",
    category: "Remote Desktop",
  },
  {
    name: "ClamAV",
    wingetId: "Cisco.ClamAV",
    category: "Security",
  },
  {
    name: "Claude Desktop",
    wingetId: "Anthropic.Claude",
    category: "AI Tools",
  },
  {
    name: "CLion",
    wingetId: "JetBrains.CLion",
    category: "Development",
  },
  {
    name: "Cloudflare WARP",
    wingetId: "Cloudflare.Warp",
    category: "Networking & VPN",
  },
  {
    name: "CMake 3.29",
    wingetId: "Kitware.CMake",
    category: "SDKs & Runtimes",
  },
  {
    name: "Continue for VS Code",
    wingetId: "Continue.Continue",
    category: "AI Tools",
  },
  {
    name: "CorelDRAW Graphics",
    wingetId: "Corel.CorelDRAW",
    category: "Graphics & Design",
  },
  {
    name: "CPUID CPU-Z",
    wingetId: "CPUID.CPU-Z",
    category: "System Monitoring",
  },
  {
    name: "CPUID HWMonitor",
    wingetId: "CPUID.HWMonitor",
    category: "System Monitoring",
  },
  {
    name: "CrystalDiskInfo",
    wingetId: "CrystalDewWorld.CrystalDiskInfo",
    category: "System Monitoring",
  },
  {
    name: "CrystalDiskMark",
    wingetId: "CrystalDewWorld.CrystalDiskMark",
    category: "System Monitoring",
  },
  {
    name: "cURL",
    wingetId: "cURL.cURL",
    category: "Development",
  },
  {
    name: "Cursor",
    wingetId: "Anysphere.Cursor",
    category: "AI Tools",
  },
  {
    name: "Darktable",
    wingetId: "darktable.darktable",
    category: "Graphics & Design",
  },
  {
    name: "Dart SDK",
    wingetId: "Dart.DartSDK",
    category: "SDKs & Runtimes",
  },
  {
    name: "Dashlane",
    wingetId: "Dashlane.Dashlane",
    category: "Security",
  },
  {
    name: "DataSpell",
    wingetId: "JetBrains.DataSpell",
    category: "Development",
  },
  {
    name: "DaVinci ALT2",
    wingetId: "Clipchamp.Clipchamp",
    category: "Content Creation",
  },
  {
    name: "DaVinci Resolve",
    wingetId: "BlackmagicDesign.DaVinciResolve",
    category: "Content Creation",
  },
  {
    name: "DBeaver CE",
    wingetId: "DBeaver.DBeaver.Community",
    category: "Development",
  },
  {
    name: "Defraggler",
    wingetId: "Piriform.Defraggler",
    category: "System Cleanup",
  },
  {
    name: "Deno Runtime",
    wingetId: "DenoLand.Deno",
    category: "SDKs & Runtimes",
  },
  {
    name: "Discord",
    wingetId: "Discord.Discord",
    category: "Communication",
  },
  {
    name: "DisplayFusion",
    wingetId: "BinaryFortress.DisplayFusion",
    category: "System Tools",
  },
  {
    name: "Ditto Clipboard",
    wingetId: "Ditto.Ditto",
    category: "Utilities",
  },
  {
    name: "Docker Compose",
    wingetId: "Docker.DockerCompose",
    category: "Virtualization",
  },
  {
    name: "Docker Desktop",
    wingetId: "Docker.DockerDesktop",
    category: "Development",
  },
  {
    name: "Dropbox",
    wingetId: "Dropbox.Dropbox",
    category: "Office & Productivity",
  },
  {
    name: "Duolingo Desktop",
    wingetId: "Duolingo.Duolingo",
    category: "Education",
  },
  {
    name: "EA App",
    wingetId: "ElectronicArts.EADesktop",
    category: "Gaming",
  },
  {
    name: "EarTrumpet",
    wingetId: "File-New-Project.EarTrumpet",
    category: "Utilities",
  },
  {
    name: "Eclipse IDE",
    wingetId: "EclipseFoundation.EclipseIDE",
    category: "Development",
  },
  {
    name: "Eclipse IDE for Java Developers",
    wingetId: "EclipseFoundation.EclipseIDE.Java",
    category: "Development",
  },
  {
    name: "Eclipse Temurin JRE 17",
    wingetId: "EclipseAdoptium.Temurin.17.JRE",
    category: "SDKs & Runtimes",
  },
  {
    name: "Eclipse Temurin JRE 21",
    wingetId: "EclipseAdoptium.Temurin.21.JRE",
    category: "SDKs & Runtimes",
  },
  {
    name: "Element",
    wingetId: "Element.Element",
    category: "Communication",
  },
  {
    name: "Epic Games Launcher",
    wingetId: "EpicGames.EpicGamesLauncher",
    category: "Gaming",
  },
  {
    name: "Evernote",
    wingetId: "Evernote.Evernote",
    category: "Office & Productivity",
  },
  {
    name: "Everything Search",
    wingetId: "voidtools.Everything",
    category: "Utilities",
  },
  {
    name: "Everything Toolbar",
    wingetId: "stnkl.EverythingToolbar",
    category: "Utilities",
  },
  {
    name: "ExplorerPatcher",
    wingetId: "valinet.ExplorerPatcher",
    category: "Utilities",
  },
  {
    name: "ExpressVPN",
    wingetId: "ExpressVPN.ExpressVPN",
    category: "Networking & VPN",
  },
  {
    name: "Fan Control",
    wingetId: "Rem0o.FanControl",
    category: "Utilities",
  },
  {
    name: "Fences",
    wingetId: "Stardock.Fences",
    category: "System Tools",
  },
  {
    name: "Figma Desktop",
    wingetId: "Figma.Figma",
    category: "Content Creation",
  },
  {
    name: "FileZilla Client",
    wingetId: "TimKosse.FileZilla.Client",
    category: "Networking & VPN",
  },
  {
    name: "Flow Launcher",
    wingetId: "Flow-Launcher.Flow-Launcher",
    category: "Utilities",
  },
  {
    name: "Flowise",
    wingetId: "FlowiseAI.Flowise",
    category: "AI Tools",
  },
  {
    name: "Flutter SDK",
    wingetId: "Google.Flutter",
    category: "Development",
  },
  {
    name: "foobar2000",
    wingetId: "PeterPawlowski.foobar2000",
    category: "Media Players",
  },
  {
    name: "Foxit Reader",
    wingetId: "Foxit.FoxitReader",
    category: "Office & Productivity",
  },
  {
    name: "GeForce Experience",
    wingetId: "Nvidia.GeForceExperience",
    category: "Gaming",
  },
  {
    name: "GeoGebra Classic",
    wingetId: "GeoGebra.Classic",
    category: "Education",
  },
  {
    name: "GIMP",
    wingetId: "GIMP.GIMP",
    category: "Content Creation",
  },
  {
    name: "Git",
    wingetId: "Git.Git",
    category: "Development",
  },
  {
    name: "GitHub CLI",
    wingetId: "GitHub.cli",
    category: "Development",
  },
  {
    name: "GitHub Desktop",
    wingetId: "GitHub.GitHubDesktop",
    category: "Development",
  },
  {
    name: "GitKraken",
    wingetId: "Axosoft.GitKraken",
    category: "Development",
  },
  {
    name: "Glary Utilities",
    wingetId: "Glarysoft.GlaryUtilities",
    category: "System Cleanup",
  },
  {
    name: "GlassWire",
    wingetId: "GlassWire.GlassWire",
    category: "Security",
  },
  {
    name: "Go 1.22 SDK",
    wingetId: "GoLang.Go.1.22",
    category: "SDKs & Runtimes",
  },
  {
    name: "Go Programming Language",
    wingetId: "GoLang.Go",
    category: "Development",
  },
  {
    name: "GOG Galaxy",
    wingetId: "GOG.Galaxy",
    category: "Gaming",
  },
  {
    name: "Google Chrome",
    wingetId: "Google.Chrome",
    category: "Browsers",
  },
  {
    name: "Google Drive",
    wingetId: "Google.GoogleDrive",
    category: "Office & Productivity",
  },
  {
    name: "GPT4All",
    wingetId: "Nomic.GPT4All",
    category: "AI Tools",
  },
  {
    name: "Gradle",
    wingetId: "Gradle.Gradle",
    category: "SDKs & Runtimes",
  },
  {
    name: "Greenshot",
    wingetId: "Greenshot.Greenshot",
    category: "Content Creation",
  },
  {
    name: "HandBrake",
    wingetId: "HandBrake.HandBrake",
    category: "Content Creation",
  },
  {
    name: "HDCleaner",
    wingetId: "KurtZimmermann.HDCleaner",
    category: "System Cleanup",
  },
  {
    name: "HDD Sentinel",
    wingetId: "HDSentinel.HardDiskSentinel",
    category: "System Monitoring",
  },
  {
    name: "HeidiSQL",
    wingetId: "HeidiSQL.HeidiSQL",
    category: "Database",
  },
  {
    name: "Helix",
    wingetId: "Helix.Helix",
    category: "Development",
  },
  {
    name: "HWINFO",
    wingetId: "REALiX.HWiNFO",
    category: "Utilities",
  },
  {
    name: "Hyper-V Manager",
    wingetId: "Microsoft.HyperV",
    category: "Virtualization",
  },
  {
    name: "ImageGlass",
    wingetId: "DuongDieuPhap.ImageGlass",
    category: "Graphics & Design",
  },
  {
    name: "Inkscape",
    wingetId: "Inkscape.Inkscape",
    category: "Content Creation",
  },
  {
    name: "Insomnia",
    wingetId: "Insomnia.Insomnia",
    category: "Development",
  },
  {
    name: "IntelliJ IDEA Community",
    wingetId: "JetBrains.IntelliJIDEA.Community",
    category: "Development",
  },
  {
    name: "Internet Download Manager",
    wingetId: "Tonec.InternetDownloadManager",
    category: "Utilities",
  },
  {
    name: "IrfanView",
    wingetId: "IrfanSkiljan.IrfanView",
    category: "Graphics & Design",
  },
  {
    name: "itch.io",
    wingetId: "itchio.itch",
    category: "Gaming",
  },
  {
    name: "iTunes",
    wingetId: "Apple.iTunes",
    category: "Media Players",
  },
  {
    name: "Jan",
    wingetId: "Menlo.Jan",
    category: "AI Tools",
  },
  {
    name: "Java SE Development Kit 8",
    wingetId: "Oracle.JDK.8",
    category: "SDKs & Runtimes",
  },
  {
    name: "Java SE Runtime Environment 8 (JRE)",
    wingetId: "Oracle.JRE.8",
    category: "SDKs & Runtimes",
  },
  {
    name: "JetBrains DataGrip",
    wingetId: "JetBrains.DataGrip",
    category: "Development",
  },
  {
    name: "JetBrains GoLand",
    wingetId: "JetBrains.GoLand",
    category: "Development",
  },
  {
    name: "JetBrains PhpStorm",
    wingetId: "JetBrains.PhpStorm",
    category: "Development",
  },
  {
    name: "JetBrains Rider",
    wingetId: "JetBrains.Rider",
    category: "Development",
  },
  {
    name: "JetBrains RubyMine",
    wingetId: "JetBrains.RubyMine",
    category: "Development",
  },
  {
    name: "Joplin",
    wingetId: "Joplin.Joplin",
    category: "Office & Productivity",
  },
  {
    name: "Kdenlive",
    wingetId: "KDE.Kdenlive",
    category: "Content Creation",
  },
  {
    name: "KeePass",
    wingetId: "DominikReichl.KeePass",
    category: "Security",
  },
  {
    name: "KeePassXC",
    wingetId: "KeePassXCTeam.KeePassXC",
    category: "Security",
  },
  {
    name: "Keka",
    wingetId: "aonez.Keka",
    category: "Compression",
  },
  {
    name: "Khan Academy Desktop",
    wingetId: "KhanAcademy.KhanAcademy",
    category: "Education",
  },
  {
    name: "Kodi",
    wingetId: "XBMCFoundation.Kodi",
    category: "Media Players",
  },
  {
    name: "Kotlin Compiler",
    wingetId: "JetBrains.Kotlin",
    category: "Development",
  },
  {
    name: "Krita",
    wingetId: "KDE.Krita",
    category: "Content Creation",
  },
  {
    name: "Kubernetes CLI",
    wingetId: "Kubernetes.kubectl",
    category: "Development",
  },
  {
    name: "LibreOffice",
    wingetId: "TheDocumentFoundation.LibreOffice",
    category: "Office & Productivity",
  },
  {
    name: "LibreWolf",
    wingetId: "LibreWolf.LibreWolf",
    category: "Browsers",
  },
  {
    name: "Lightworks",
    wingetId: "LWKS.Lightworks",
    category: "Content Creation",
  },
  {
    name: "LLVM/Clang 18",
    wingetId: "LLVM.LLVM.18",
    category: "SDKs & Runtimes",
  },
  {
    name: "LM Studio",
    wingetId: "ElementLabs.LMStudio",
    category: "AI Tools",
  },
  {
    name: "Logitech Options",
    wingetId: "Logitech.Options",
    category: "Office & Productivity",
  },
  {
    name: "Logseq",
    wingetId: "Logseq.Logseq",
    category: "Office & Productivity",
  },
  {
    name: "Lutris",
    wingetId: "Lutris.Lutris",
    category: "Gaming",
  },
  {
    name: "Malwarebytes",
    wingetId: "Malwarebytes.Malwarebytes",
    category: "Security",
  },
  {
    name: "Maven",
    wingetId: "Apache.Maven",
    category: "SDKs & Runtimes",
  },
  {
    name: "Media Player Classic BE",
    wingetId: "MPC-BE.MPC-BE",
    category: "Media Players",
  },
  {
    name: "MEGA Sync",
    wingetId: "Mega.MEGASync",
    category: "Cloud Storage",
  },
  {
    name: "MemTest86",
    wingetId: "PassMark.MemTest86",
    category: "System Monitoring",
  },
  {
    name: "Mendeley Desktop",
    wingetId: "Mendeley.MendeleyDesktop",
    category: "Education",
  },
  {
    name: "Microsoft .NET Framework Dev Pack 4.8",
    wingetId: "Microsoft.DotNet.Framework.DeveloperPack_4.8",
    category: "SDKs & Runtimes",
  },
  {
    name: "Microsoft .NET Runtime 8",
    wingetId: "Microsoft.DotNet.Runtime.8",
    category: "SDKs & Runtimes",
  },
  {
    name: "Microsoft .NET SDK 8",
    wingetId: "Microsoft.DotNet.SDK.8",
    category: "SDKs & Runtimes",
  },
  {
    name: "Microsoft .NET SDK 9",
    wingetId: "Microsoft.DotNet.SDK.9",
    category: "SDKs & Runtimes",
  },
  {
    name: "Microsoft Edge",
    wingetId: "Microsoft.Edge",
    category: "Browsers",
  },
  {
    name: "Microsoft OneDrive",
    wingetId: "Microsoft.OneDrive",
    category: "Office & Productivity",
  },
  {
    name: "Microsoft Teams",
    wingetId: "Microsoft.Teams",
    category: "Communication",
  },
  {
    name: "Microsoft Teams Classic",
    wingetId: "Microsoft.Teams.Classic",
    category: "Communication",
  },
  {
    name: "MobaXterm",
    wingetId: "Mobatek.MobaXterm",
    category: "Networking & VPN",
  },
  {
    name: "MongoDB Compass",
    wingetId: "MongoDB.Compass",
    category: "Database",
  },
  {
    name: "Mozilla Firefox",
    wingetId: "Mozilla.Firefox",
    category: "Browsers",
  },
  {
    name: "MPC-HC",
    wingetId: "clsid2.mpc-hc",
    category: "Media Players",
  },
  {
    name: "mpv",
    wingetId: "mpv.mpv",
    category: "Media Players",
  },
  {
    name: "MSI Afterburner",
    wingetId: "Guru3D.Afterburner",
    category: "Utilities",
  },
  {
    name: "Mullvad VPN",
    wingetId: "MullvadVPN.MullvadVPN",
    category: "Networking & VPN",
  },
  {
    name: "Multipass",
    wingetId: "Canonical.Multipass",
    category: "Virtualization",
  },
  {
    name: "MusicBee",
    wingetId: "MusicBee.MusicBee",
    category: "Media Players",
  },
  {
    name: "MySQL Workbench",
    wingetId: "Oracle.MySQLWorkbench",
    category: "Database",
  },
  {
    name: "NanaZip",
    wingetId: "M2Team.NanaZip",
    category: "Compression",
  },
  {
    name: "Natron",
    wingetId: "Natron.Natron",
    category: "Content Creation",
  },
  {
    name: "Navicat Premium",
    wingetId: "PremiumSoft.NavicatPremium",
    category: "Database",
  },
  {
    name: "Neovim",
    wingetId: "Neovim.Neovim",
    category: "Development",
  },
  {
    name: "NetBeans 21",
    wingetId: "Apache.NetBeans.21",
    category: "Development",
  },
  {
    name: "Nextcloud Desktop",
    wingetId: "Nextcloud.NextcloudDesktop",
    category: "Cloud Storage",
  },
  {
    name: "ngrok",
    wingetId: "ngrok.ngrok",
    category: "Networking & VPN",
  },
  {
    name: "Nilesoft Shell",
    wingetId: "Nilesoft.Shell",
    category: "System Tools",
  },
  {
    name: "Ninja Build",
    wingetId: "Ninja-build.Ninja",
    category: "SDKs & Runtimes",
  },
  {
    name: "Node.js 20 LTS",
    wingetId: "OpenJS.NodeJS",
    category: "SDKs & Runtimes",
  },
  {
    name: "Node.js LTS",
    wingetId: "OpenJS.NodeJS.LTS",
    category: "Development",
  },
  {
    name: "NoMachine",
    wingetId: "NoMachine.NoMachine",
    category: "Remote Desktop",
  },
  {
    name: "Nomacs",
    wingetId: "nomacs.nomacs",
    category: "Graphics & Design",
  },
  {
    name: "NordVPN",
    wingetId: "NordSecurity.NordVPN",
    category: "Networking & VPN",
  },
  {
    name: "Notepad++",
    wingetId: "Notepad++.Notepad++",
    category: "Utilities",
  },
  {
    name: "Notion",
    wingetId: "Notion.Notion",
    category: "Office & Productivity",
  },
  {
    name: "OBS Studio",
    wingetId: "OBSProject.OBSStudio",
    category: "Content Creation",
  },
  {
    name: "Obsidian",
    wingetId: "Obsidian.Obsidian",
    category: "Office & Productivity",
  },
  {
    name: "OCCT",
    wingetId: "OCBase.OCCT",
    category: "System Monitoring",
  },
  {
    name: "Ollama",
    wingetId: "Ollama.Ollama",
    category: "AI Tools",
  },
  {
    name: "OnlyOffice Desktop",
    wingetId: "Ascensio.OnlyOffice",
    category: "Office & Productivity",
  },
  {
    name: "OpenJDK 11 (Temurin 11)",
    wingetId: "EclipseAdoptium.Temurin.11.JDK",
    category: "SDKs & Runtimes",
  },
  {
    name: "OpenJDK 17 (Microsoft)",
    wingetId: "Microsoft.OpenJDK.17",
    category: "SDKs & Runtimes",
  },
  {
    name: "OpenJDK 21",
    wingetId: "Microsoft.OpenJDK.21",
    category: "Development",
  },
  {
    name: "OpenJDK 21 (Eclipse Temurin 21)",
    wingetId: "EclipseAdoptium.Temurin.21.JDK",
    category: "SDKs & Runtimes",
  },
  {
    name: "OpenJDK 8 (Temurin 8)",
    wingetId: "EclipseAdoptium.Temurin.8.JDK",
    category: "SDKs & Runtimes",
  },
  {
    name: "OpenVPN",
    wingetId: "OpenVPNTechnologies.OpenVPN",
    category: "Networking & VPN",
  },
  {
    name: "Opera",
    wingetId: "Opera.Opera",
    category: "Browsers",
  },
  {
    name: "Oracle JDK 17",
    wingetId: "Oracle.JDK.17",
    category: "SDKs & Runtimes",
  },
  {
    name: "Oracle JDK 21",
    wingetId: "Oracle.JDK.21",
    category: "SDKs & Runtimes",
  },
  {
    name: "Oracle VirtualBox",
    wingetId: "Oracle.VirtualBox",
    category: "Virtualization",
  },
  {
    name: "Overwolf",
    wingetId: "Overwolf.Overwolf",
    category: "Gaming",
  },
  {
    name: "Paint.NET",
    wingetId: "dotPDN.PaintDotNet",
    category: "Content Creation",
  },
  {
    name: "Parsec",
    wingetId: "Parsec.Parsec",
    category: "Remote Desktop",
  },
  {
    name: "pCloud Drive",
    wingetId: "pCloud.pCloudDrive",
    category: "Cloud Storage",
  },
  {
    name: "PeaZip",
    wingetId: "Giorgiotani.Peazip",
    category: "Compression",
  },
  {
    name: "Perplexity Desktop",
    wingetId: "Perplexity.Perplexity",
    category: "AI Tools",
  },
  {
    name: "pgAdmin 4",
    wingetId: "dpage.pgAdmin",
    category: "Database",
  },
  {
    name: "PHP 8.3",
    wingetId: "PHP.PHP.8.3",
    category: "SDKs & Runtimes",
  },
  {
    name: "PlatformIO Core",
    wingetId: "PlatformIO.PlatformIOCore",
    category: "SDKs & Runtimes",
  },
  {
    name: "Playnite",
    wingetId: "Playnite.Playnite",
    category: "Gaming",
  },
  {
    name: "Plex",
    wingetId: "Plex.Plex",
    category: "Media Players",
  },
  {
    name: "Podman",
    wingetId: "RedHat.Podman",
    category: "Virtualization",
  },
  {
    name: "PortableApps Platform (Direct)",
    wingetId: "PortableApps.Platform",
    category: "Direct Downloads",
  },
  {
    name: "Postman",
    wingetId: "Postman.Postman",
    category: "Development",
  },
  {
    name: "PotPlayer",
    wingetId: "Daum.PotPlayer",
    category: "Media Players",
  },
  {
    name: "PowerShell",
    wingetId: "Microsoft.PowerShell",
    category: "Development",
  },
  {
    name: "PowerToys",
    wingetId: "Microsoft.PowerToys",
    category: "Utilities",
  },
  {
    name: "Prism Launcher",
    wingetId: "PrismLauncher.PrismLauncher",
    category: "Gaming",
  },
  {
    name: "Process Explorer",
    wingetId: "Microsoft.Sysinternals.ProcessExplorer",
    category: "Utilities",
  },
  {
    name: "Process Monitor",
    wingetId: "Microsoft.Sysinternals.ProcessMonitor",
    category: "Utilities",
  },
  {
    name: "Proton Pass",
    wingetId: "Proton.ProtonPass",
    category: "Security",
  },
  {
    name: "ProtonVPN",
    wingetId: "Proton.ProtonVPN",
    category: "Security",
  },
  {
    name: "PuTTY",
    wingetId: "PuTTY.PuTTY",
    category: "Development",
  },
  {
    name: "PyCharm Community",
    wingetId: "JetBrains.PyCharm.Community",
    category: "Development",
  },
  {
    name: "Python 3.11",
    wingetId: "Python.Python.3.11",
    category: "SDKs & Runtimes",
  },
  {
    name: "Python 3.12",
    wingetId: "Python.Python.3.12",
    category: "SDKs & Runtimes",
  },
  {
    name: "Python 3.13",
    wingetId: "Python.Python.3.13",
    category: "Development",
  },
  {
    name: "QEMU",
    wingetId: "SoftwareFreedomConservancy.QEMU",
    category: "Virtualization",
  },
  {
    name: "Qt Creator",
    wingetId: "Qt.QtCreator",
    category: "Development",
  },
  {
    name: "QuickLook",
    wingetId: "QL-Win.QuickLook",
    category: "System Tools",
  },
  {
    name: "Rainmeter",
    wingetId: "Rainmeter.Rainmeter",
    category: "System Tools",
  },
  {
    name: "RawTherapee",
    wingetId: "RawTherapee.RawTherapee",
    category: "Graphics & Design",
  },
  {
    name: "Redis Insight",
    wingetId: "Redis.RedisInsight",
    category: "Database",
  },
  {
    name: "Resilio Sync",
    wingetId: "Resilio.ResilioSync",
    category: "Cloud Storage",
  },
  {
    name: "Revo Uninstaller",
    wingetId: "VSRevoGroup.RevoUninstaller",
    category: "Utilities",
  },
  {
    name: "Rosetta Stone",
    wingetId: "RosettaStone.RosettaStone",
    category: "Education",
  },
  {
    name: "Ruby 3.3 (with DevKit)",
    wingetId: "RubyInstallerTeam.RubyWithDevKit.3.3",
    category: "SDKs & Runtimes",
  },
  {
    name: "Rufus",
    wingetId: "Rufus.Rufus",
    category: "Utilities",
  },
  {
    name: "Rust",
    wingetId: "Rustlang.Rustup",
    category: "Development",
  },
  {
    name: "RustDesk",
    wingetId: "RustDesk.RustDesk",
    category: "Remote Desktop",
  },
  {
    name: "Sandboxie-Plus",
    wingetId: "Sandboxie.Plus",
    category: "Virtualization",
  },
  {
    name: "Scoop",
    wingetId: "ScoopInstaller.Scoop",
    category: "System Tools",
  },
  {
    name: "Scratch Desktop",
    wingetId: "MIT.Scratch",
    category: "Education",
  },
  {
    name: "Scrcpy",
    wingetId: "Scrcpy.Scrcpy",
    category: "Utilities",
  },
  {
    name: "Sequel Ace",
    wingetId: "Sequel-Ace.SequalAce",
    category: "Database",
  },
  {
    name: "ShareX",
    wingetId: "ShareX.ShareX",
    category: "Content Creation",
  },
  {
    name: "Shotcut",
    wingetId: "Meltytech.Shotcut",
    category: "Content Creation",
  },
  {
    name: "Signal",
    wingetId: "OpenWhisperSystems.Signal",
    category: "Communication",
  },
  {
    name: "Skype",
    wingetId: "Microsoft.Skype",
    category: "Communication",
  },
  {
    name: "Slack",
    wingetId: "SlackTechnologies.Slack",
    category: "Communication",
  },
  {
    name: "SmartFTP",
    wingetId: "SmartSoft.SmartFTP",
    category: "Networking & VPN",
  },
  {
    name: "SourceTree",
    wingetId: "Atlassian.SourceTree",
    category: "Development",
  },
  {
    name: "Speccy",
    wingetId: "Piriform.Speccy",
    category: "System Monitoring",
  },
  {
    name: "Spotify",
    wingetId: "Spotify.Spotify",
    category: "Media Players",
  },
  {
    name: "SQLite Browser",
    wingetId: "DBBrowserForSQLite.DBBrowserForSQLite",
    category: "Database",
  },
  {
    name: "Stable Diffusion WebUI",
    wingetId: "AUTOMATIC1111.StableDiffusionWebUI",
    category: "AI Tools",
  },
  {
    name: "Standard Notes",
    wingetId: "StandardNotes.StandardNotes",
    category: "Office & Productivity",
  },
  {
    name: "StartAllBack",
    wingetId: "StartIsBack.StartAllBack",
    category: "Utilities",
  },
  {
    name: "Steam",
    wingetId: "Valve.Steam",
    category: "Gaming",
  },
  {
    name: "Stellarium",
    wingetId: "Stellarium.Stellarium",
    category: "Education",
  },
  {
    name: "Sublime Text 4",
    wingetId: "SublimeHQ.SublimeText.4",
    category: "Development",
  },
  {
    name: "SumatraPDF",
    wingetId: "SumatraPDF.SumatraPDF",
    category: "Office & Productivity",
  },
  {
    name: "Supremo",
    wingetId: "Supremo.Supremo",
    category: "Remote Desktop",
  },
  {
    name: "Sync.com",
    wingetId: "Sync.Sync",
    category: "Cloud Storage",
  },
  {
    name: "Sysinternals Suite (Direct ZIP)",
    wingetId: "Microsoft.SysinternalsSuite.Direct",
    category: "Direct Downloads",
  },
  {
    name: "TablePlus",
    wingetId: "TablePlus.TablePlus",
    category: "Database",
  },
  {
    name: "Tailscale",
    wingetId: "Tailscale.Tailscale",
    category: "Networking & VPN",
  },
  {
    name: "TeamViewer",
    wingetId: "TeamViewer.TeamViewer",
    category: "Remote Desktop",
  },
  {
    name: "TechPowerUp GPU-Z",
    wingetId: "TechPowerUp.GPU-Z",
    category: "System Monitoring",
  },
  {
    name: "Telegram Desktop",
    wingetId: "Telegram.TelegramDesktop",
    category: "Communication",
  },
  {
    name: "Terraform",
    wingetId: "Hashicorp.Terraform",
    category: "Development",
  },
  {
    name: "Thunderbird",
    wingetId: "Mozilla.Thunderbird",
    category: "Communication",
  },
  {
    name: "Tor Browser",
    wingetId: "TorProject.TorBrowser",
    category: "Browsers",
  },
  {
    name: "TranslucentTB",
    wingetId: "TranslucentTB.TranslucentTB",
    category: "System Tools",
  },
  {
    name: "TreeSize Free",
    wingetId: "JAMSoftware.TreeSize.Free",
    category: "Utilities",
  },
  {
    name: "Trello Desktop",
    wingetId: "Trello.Trello",
    category: "Office & Productivity",
  },
  {
    name: "Tresorit",
    wingetId: "Tresorit.Tresorit",
    category: "Cloud Storage",
  },
  {
    name: "Ubisoft Connect",
    wingetId: "Ubisoft.Connect",
    category: "Gaming",
  },
  {
    name: "UltraVNC",
    wingetId: "uvnc.UltraVNC",
    category: "Remote Desktop",
  },
  {
    name: "Ungoogled Chromium",
    wingetId: "eloston.ungoogled-chromium",
    category: "Browsers",
  },
  {
    name: "Unity Hub",
    wingetId: "Unity.UnityHub",
    category: "SDKs & Runtimes",
  },
  {
    name: "Vagrant",
    wingetId: "Hashicorp.Vagrant",
    category: "Virtualization",
  },
  {
    name: "VeraCrypt",
    wingetId: "IDRIX.VeraCrypt",
    category: "Security",
  },
  {
    name: "VeraCrypt",
    wingetId: "VeraCrypt.VeraCrypt",
    category: "Security",
  },
  {
    name: "Viber",
    wingetId: "Viber.Viber",
    category: "Communication",
  },
  {
    name: "Visual Studio Build Tools 2022",
    wingetId: "Microsoft.VisualStudio.2022.BuildTools",
    category: "Development",
  },
  {
    name: "Visual Studio Build Tools 2026",
    wingetId: "Microsoft.VisualStudio.2026.BuildTools",
    category: "Development",
  },
  {
    name: "Visual Studio Code",
    wingetId: "Microsoft.VisualStudioCode",
    category: "Development",
  },
  {
    name: "Visual Studio Code Insiders",
    wingetId: "Microsoft.VisualStudioCode.Insiders",
    category: "Development",
  },
  {
    name: "Visual Studio Community 2022",
    wingetId: "Microsoft.VisualStudio.2022.Community",
    category: "Development",
  },
  {
    name: "Visual Studio Community 2026",
    wingetId: "Microsoft.VisualStudio.2026.Community",
    category: "Development",
  },
  {
    name: "Visual Studio Enterprise 2022",
    wingetId: "Microsoft.VisualStudio.2022.Enterprise",
    category: "Development",
  },
  {
    name: "Visual Studio Enterprise 2026",
    wingetId: "Microsoft.VisualStudio.2026.Enterprise",
    category: "Development",
  },
  {
    name: "Visual Studio Preview 2026",
    wingetId: "Microsoft.VisualStudio.2026.Preview",
    category: "Development",
  },
  {
    name: "Visual Studio Professional 2022",
    wingetId: "Microsoft.VisualStudio.2022.Professional",
    category: "Development",
  },
  {
    name: "Visual Studio Professional 2026",
    wingetId: "Microsoft.VisualStudio.2026.Professional",
    category: "Development",
  },
  {
    name: "Vivaldi",
    wingetId: "VivaldiTechnologies.Vivaldi",
    category: "Browsers",
  },
  {
    name: "VLC Media Player",
    wingetId: "VideoLAN.VLC",
    category: "Media Players",
  },
  {
    name: "VMware Workstation Pro",
    wingetId: "VMware.WorkstationPro",
    category: "Virtualization",
  },
  {
    name: "Waterfox",
    wingetId: "Waterfox.Waterfox",
    category: "Browsers",
  },
  {
    name: "WebStorm",
    wingetId: "JetBrains.WebStorm",
    category: "Development",
  },
  {
    name: "WeChat",
    wingetId: "Tencent.WeChat",
    category: "Communication",
  },
  {
    name: "WhatsApp",
    wingetId: "WhatsApp.WhatsApp",
    category: "Communication",
  },
  {
    name: "Whisper Desktop",
    wingetId: "Const-me.Whisper",
    category: "AI Tools",
  },
  {
    name: "Winamp",
    wingetId: "Nullsoft.Winamp",
    category: "Media Players",
  },
  {
    name: "Windows SDK 10",
    wingetId: "Microsoft.WindowsSDK.10.0.22621",
    category: "SDKs & Runtimes",
  },
  {
    name: "Windows Terminal",
    wingetId: "Microsoft.WindowsTerminal",
    category: "Development",
  },
  {
    name: "WingetUI",
    wingetId: "MartiCliment.UniGetUI",
    category: "System Tools",
  },
  {
    name: "WinRAR",
    wingetId: "RARLab.WinRAR",
    category: "Compression",
  },
  {
    name: "WinSCP",
    wingetId: "WinSCP.WinSCP",
    category: "Development",
  },
  {
    name: "WinZip",
    wingetId: "Corel.WinZip",
    category: "Compression",
  },
  {
    name: "WireGuard",
    wingetId: "WireGuard.WireGuard",
    category: "Networking & VPN",
  },
  {
    name: "Wireshark",
    wingetId: "WiresharkFoundation.Wireshark",
    category: "Networking & VPN",
  },
  {
    name: "Wise Disk Cleaner",
    wingetId: "WiseCleaner.WiseDiskCleaner",
    category: "System Cleanup",
  },
  {
    name: "WizTree",
    wingetId: "AntibodySoftware.WizTree",
    category: "Utilities",
  },
  {
    name: "WPS Office",
    wingetId: "Kingsoft.WPSOffice",
    category: "Office & Productivity",
  },
  {
    name: "Xbox App",
    wingetId: "Microsoft.XboxApp",
    category: "Gaming",
  },
  {
    name: "XnView MP",
    wingetId: "XnSoft.XnViewMP",
    category: "Graphics & Design",
  },
  {
    name: "ZeroTier One",
    wingetId: "ZeroTier.ZeroTierOne",
    category: "Networking & VPN",
  },
  {
    name: "ZoneAlarm Free",
    wingetId: "CheckPoint.ZoneAlarm",
    category: "Security",
  },
  {
    name: "Zoom",
    wingetId: "Zoom.Zoom",
    category: "Communication",
  },
  {
    name: "Zotero",
    wingetId: "DigitalScholar.Zotero",
    category: "Education",
  },
];

export const profiles: Profile[] = [
  {
    name: "Student",
    description: "Productivity and study essentials",
    appCount: 11,
    builtin: true,
    apps: [
      "Google Chrome",
      "Visual Studio Code",
      "LibreOffice",
      "VLC Media Player",
      "7-Zip",
      "Zoom",
      "Notion",
      "Anki",
      "Zotero",
      "Obsidian",
      "SumatraPDF",
    ],
  },
  {
    name: "Gamer",
    description: "Gaming platforms and streaming tools",
    appCount: 10,
    builtin: true,
    apps: [
      "Steam",
      "Discord",
      "OBS Studio",
      "7-Zip",
      "Google Chrome",
      "Epic Games Launcher",
      "GOG Galaxy",
      "Ubisoft Connect",
      "Playnite",
      "GeForce Experience",
    ],
  },
  {
    name: "Mobile Developer",
    description: "Android & cross-platform mobile stack — Studio, JDK, Kotlin, Flutter, SDK tools",
    appCount: 14,
    builtin: true,
    apps: [
      "Android Studio",
      "OpenJDK 21",
      "Adoptium Temurin 17",
      "Android SDK Platform Tools",
      "Android NDK",
      "Gradle",
      "Kotlin Compiler",
      "Flutter SDK",
      "Dart SDK",
      "Git",
      "GitHub CLI",
      "Visual Studio Code",
      "Postman",
      "Scrcpy",
    ],
  },
  {
    name: "Data / Python",
    description: "Python, datasci & DB — Python 3.13/12, Jupyter, Anaconda-style, DBs",
    appCount: 11,
    builtin: true,
    apps: [
      "Python 3.13",
      "Python 3.12",
      "Visual Studio Code",
      "DataSpell",
      "DBeaver CE",
      "MySQL Workbench",
      "pgAdmin 4",
      "Docker Desktop",
      "Git",
      "PowerShell",
      "Cursor",
    ],
  },
  {
    name: "Technician",
    description: "Clean Windows — browsers, Office, drivers, utilities after formatting",
    appCount: 13,
    builtin: true,
    apps: [
      "Google Chrome",
      "Mozilla Firefox",
      "7-Zip",
      "VLC Media Player",
      "LibreOffice",
      "Adobe Acrobat Reader",
      "SumatraPDF",
      "Bitwarden",
      "Notepad++",
      "Rufus",
      "AnyDesk",
      "Zoom",
      "Malwarebytes",
    ],
  },
];
